all:
	kikit panelize \
	    --layout 'vspace: 2mm; rows: 20; cols: 4' \
	    --tabs 'type: fixed; vcount: 0' \
	    --cuts 'type: vcuts; layer: Edge.Cuts' \
	    --framing 'type: railslr; hspace: 0mm; width: 7mm' \
	    spacer.kicad_pcb panel.kicad_pcb
